#!/bin/sh
# Init script for Yandex Station provider Docker dev environment.
# Auto-generated by ma-provider-tools — do not edit manually.
set -e

echo "==> Setting up Yandex Station provider..."
# Locate MA providers directory inside the container venv
PROVIDERS_DIR=$(/app/venv/bin/python3 -c \
    "import music_assistant.providers, os; print(os.path.dirname(music_assistant.providers.__file__))")

# Remove any existing provider (image may bundle one), then symlink ours
rm -rf "${PROVIDERS_DIR}/yandex_station"
ln -s /tmp/provider "${PROVIDERS_DIR}/yandex_station"
echo "==> Provider linked: ${PROVIDERS_DIR}/yandex_station"

# Install provider-specific runtime dependencies (skips music_assistant itself)
DEPS=$(/app/venv/bin/python3 - <<'PYEOF'
import sys
try:
    import tomllib
except ImportError:
    import tomli as tomllib
try:
    with open("/tmp/pyproject.toml", "rb") as f:
        data = tomllib.load(f)
    deps = [
        d for d in data.get("project", {}).get("dependencies", [])
        if not d.lower().startswith("music_assistant")
    ]
    print(" ".join(deps))
except Exception:
    pass
PYEOF
)
if [ -n "$DEPS" ]; then
    echo "==> Installing provider dependencies: $DEPS"
    # The official ghcr.io/music-assistant/server image ships uv but no pip
    # in the venv, so the bare `pip install` path crashes on
    # `/app/venv/bin/pip: not found`. Prefer uv when available; fall back
    # to pip for any image that still has it.
    if [ -x /app/venv/bin/uv ]; then
        /app/venv/bin/uv pip install --quiet --index-strategy unsafe-best-match --python /app/venv/bin/python $DEPS
    else
        /app/venv/bin/pip install --quiet $DEPS
    fi
fi

# The nightly image can bundle other Yandex providers that still pin an older
# ya-passport-auth release. Music Assistant installs manifest requirements at
# startup, so those stale pins would downgrade the version installed above.
# Align only the container's bundled Yandex manifests with this provider's
# declared pin; the bind-mounted provider remains read-only and unchanged.
PASSPORT_REQ=$(/app/venv/bin/python3 - <<'PYEOF'
import tomllib

with open("/tmp/pyproject.toml", "rb") as f:
    dependencies = tomllib.load(f).get("project", {}).get("dependencies", [])
print(next((dep for dep in dependencies if dep.lower().startswith("ya-passport-auth")), ""))
PYEOF
)
if [ -n "$PASSPORT_REQ" ]; then
    /app/venv/bin/python3 - "$PROVIDERS_DIR" "$PASSPORT_REQ" <<'PYEOF'
import json
import sys
from pathlib import Path

providers_dir = Path(sys.argv[1])
passport_requirement = sys.argv[2]
for manifest_path in providers_dir.glob("yandex_*/manifest.json"):
    if manifest_path.parent.is_symlink():
        continue
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    requirements = manifest.get("requirements", [])
    aligned = [
        passport_requirement if req.lower().startswith("ya-passport-auth") else req
        for req in requirements
    ]
    if aligned != requirements:
        manifest["requirements"] = aligned
        manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
PYEOF
fi

echo "==> Starting Music Assistant..."
exec /usr/local/bin/entrypoint.sh --data-dir /data --cache-dir /data/.cache
